package com.onmobile.apps.ringbacktones.genericcache.interfaces;

public enum CacheNamesEnum
{
	BULK_PROMO_SMS_CACHE,
	CHARGE_CLASS_CACHE,
	CHARGE_CLASS_MAP_CACHE,
	COS_CACHE,
	PARAMETERS_CACHE,
	PREDEFINED_GROUP,
	RBT_TEXT_CACHE,
	SITE_PREFIX_CACHE,
	SUBSCRIPTION_CLASS_CACHE
}
