//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 12:55:29 PM IST 
//


package com.onmobile.android.jaxb.gift;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}clip"/>
 *       &lt;/sequence>
 *       &lt;attribute name="noOfclips" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clip"
})
@XmlRootElement(name = "clips")
public class Clips {

    @XmlElement(required = true)
    protected Clip clip;
    @XmlAttribute(required = true)
    protected BigInteger noOfclips;

    /**
     * Gets the value of the clip property.
     * 
     * @return
     *     possible object is
     *     {@link Clip }
     *     
     */
    public Clip getClip() {
        return clip;
    }

    /**
     * Sets the value of the clip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clip }
     *     
     */
    public void setClip(Clip value) {
        this.clip = value;
    }

    /**
     * Gets the value of the noOfclips property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNoOfclips() {
        return noOfclips;
    }

    /**
     * Sets the value of the noOfclips property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNoOfclips(BigInteger value) {
        this.noOfclips = value;
    }

}
