/**
 * This is generated code and SHOULD NOT BE MODIFIED BY HAND. To change the transactions or the fields below, please regenerate.
 * If you have any questions, contact the Morpheus team.
 */
package com.onmobile.apps.ringbacktones.common;

import java.io.IOException;

import com.onmobile.reporting.framework.capture.api.Configuration;
import com.onmobile.reporting.framework.capture.api.ReportingException;
/**Interoperator copy transaction report. 
 */

public class ViralPromotionEventLogger extends com.onmobile.reporting.framework.capture.api.TransactionBase {

	/**
	 * @param config Configuration of this logging system. Most important configuration item is the filepath to which logging should be done.
	 * @throws IOException if the initial log file cannot be created
	 */
	public ViralPromotionEventLogger(Configuration config) throws java.io.IOException {
		super();
		initialize(config);
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getProduct()
	 */
	public String getProduct() {
		return "ViralPromotionTransLogger";
	}
	
	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getVersion()
	 */
	public String getVersion() {
		return "1.0.0";
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getFieldHeadings()
	 */
	protected String getFieldHeadings() {
		return "TIMESTAMP,TRANSTYPE,CALLER,CALLED,CLIP_ID";
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#isAutoGeneratedTimestamp()
	 */
	protected boolean isAutoGeneratedTimestamp() {
		return false;
	}

	/**
	 * To store the viral promotion transactions. 
	 *
	 * @param caller Msisdn of caller 
	 * @param called Called party Msisdn 
	 * @param clipId Clip Id of the content 
	 * @param timestamp Record time stamp of this transaction 
	*/
	public void ViralPromotionLogger(
		 String caller
		,String called
		,String clipId
		,java.util.Date timestamp
	) throws ReportingException {
		StringBuffer buff = new StringBuffer();
		append(buff, timestamp);
		nextField(buff);// write field separator
		append(buff, "ViralPromotionLogger", false); // transType
		nextField(buff);// write field separator
		append(buff, caller, true);
		nextField(buff);// write field separator
		append(buff, called, true);
		nextField(buff);// write field separator
		append(buff, clipId, true);
		write(buff); // write record to file
	} // end of transaction function

}
