//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.28 at 12:24:43 PM IST 
//


package com.onmobile.apps.ringbacktones.webservice.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="response" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subscriber" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="CONSENT_SUBSCRIPTION_INSERT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="VOLUNTARY" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="access_count" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="activated_by" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="activation_info" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="can_allow" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="circle_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="cos_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="is_prepaid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="is_valid_prefix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="num_max_selections" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="pack" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="pca" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ref_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="subscriber_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="subscription_class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="user_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="deactivated_by" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="last_deactivation_info" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="start_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="end_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="next_charging_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="last_deactivation_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="activation_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="protocolNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="protocolStaticText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="next_billing_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="charge_details" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="last_charge_amount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="is_freemium_subscriber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="is_freemium" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="num_free_songs_left" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="is_uds_on" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="is_refundable" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="tobe_act_offer_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="offer_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="imei_no" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="scrn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="scrs" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DELAY_DEACT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="library" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="settings" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="contents" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{}content" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="no_of_default_settings" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="no_of_settings" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="no_of_special_settings" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="downloads" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="contents" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{}content" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="recent_selections" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="charge_class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="no_of_downloads" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="no_of_active_downloads" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="no_of_free_songs_left" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="is_album_user" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="is_recent_sel_consent" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="provide_default_loop_option" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="is_musicbox_default_setting_pending" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="is_clip_default_setting_pending" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="total_downloads" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="next_charge_class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="next_selection_amount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="consent" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="event_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="mode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="plan_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="price" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="srvClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="srvId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="transID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response",
    "subscriber",
    "library",
    "consent"
})
@XmlRootElement(name = "rbt")
public class Rbt {

    @XmlElement(required = true)
    protected String response;
    protected Rbt.Subscriber subscriber;
    protected Rbt.Library library;
    protected Rbt.Consent consent;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponse(String value) {
        this.response = value;
    }

    /**
     * Gets the value of the subscriber property.
     * 
     * @return
     *     possible object is
     *     {@link Rbt.Subscriber }
     *     
     */
    public Rbt.Subscriber getSubscriber() {
        return subscriber;
    }

    /**
     * Sets the value of the subscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rbt.Subscriber }
     *     
     */
    public void setSubscriber(Rbt.Subscriber value) {
        this.subscriber = value;
    }

    /**
     * Gets the value of the library property.
     * 
     * @return
     *     possible object is
     *     {@link Rbt.Library }
     *     
     */
    public Rbt.Library getLibrary() {
        return library;
    }

    /**
     * Sets the value of the library property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rbt.Library }
     *     
     */
    public void setLibrary(Rbt.Library value) {
        this.library = value;
    }

    /**
     * Gets the value of the consent property.
     * 
     * @return
     *     possible object is
     *     {@link Rbt.Consent }
     *     
     */
    public Rbt.Consent getConsent() {
        return consent;
    }

    /**
     * Sets the value of the consent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rbt.Consent }
     *     
     */
    public void setConsent(Rbt.Consent value) {
        this.consent = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="event_type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="mode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="plan_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="price" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="srvClass" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="srvId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="transID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Consent {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "event_type")
        protected String eventType;
        @XmlAttribute
        protected String language;
        @XmlAttribute
        protected String mode;
        @XmlAttribute(name = "plan_id")
        protected String planId;
        @XmlAttribute
        protected String price;
        @XmlAttribute
        protected String srvClass;
        @XmlAttribute
        protected String srvId;
        @XmlAttribute
        protected String transID;
        @XmlAttribute(name = "value")
        protected String consentValue;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the eventType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEventType() {
            return eventType;
        }

        /**
         * Sets the value of the eventType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEventType(String value) {
            this.eventType = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

        /**
         * Gets the value of the planId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanId() {
            return planId;
        }

        /**
         * Sets the value of the planId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanId(String value) {
            this.planId = value;
        }

        /**
         * Gets the value of the price property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrice(String value) {
            this.price = value;
        }

        /**
         * Gets the value of the srvClass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrvClass() {
            return srvClass;
        }

        /**
         * Sets the value of the srvClass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrvClass(String value) {
            this.srvClass = value;
        }

        /**
         * Gets the value of the srvId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrvId() {
            return srvId;
        }

        /**
         * Sets the value of the srvId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrvId(String value) {
            this.srvId = value;
        }

        /**
         * Gets the value of the transID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransID() {
            return transID;
        }

        /**
         * Sets the value of the transID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransID(String value) {
            this.transID = value;
        }

        /**
         * Gets the value of the consentValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConsentValue() {
            return consentValue;
        }

        /**
         * Sets the value of the consentValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConsentValue(String value) {
            this.consentValue = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="settings" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="contents" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{}content" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="no_of_default_settings" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="no_of_settings" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="no_of_special_settings" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="downloads" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="contents" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{}content" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="recent_selections" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="charge_class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="no_of_downloads" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="no_of_active_downloads" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="no_of_free_songs_left" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="is_album_user" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="is_recent_sel_consent" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="provide_default_loop_option" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="is_musicbox_default_setting_pending" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="is_clip_default_setting_pending" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="total_downloads" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="next_charge_class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="next_selection_amount" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "settings",
        "downloads"
    })
    public static class Library {

        protected Rbt.Library.Settings settings;
        protected Rbt.Library.Downloads downloads;
        @XmlAttribute(name = "no_of_free_songs_left")
        protected String noOfFreeSongsLeft;
        @XmlAttribute(name = "is_album_user")
        protected String isAlbumUser;
        @XmlAttribute(name = "is_recent_sel_consent")
        protected String isRecentSelConsent;
        @XmlAttribute(name = "provide_default_loop_option")
        protected String provideDefaultLoopOption;
        @XmlAttribute(name = "is_musicbox_default_setting_pending")
        protected String isMusicboxDefaultSettingPending;
        @XmlAttribute(name = "is_clip_default_setting_pending")
        protected String isClipDefaultSettingPending;
        @XmlAttribute(name = "total_downloads")
        protected String totalDownloads;
        @XmlAttribute(name = "next_charge_class")
        protected String nextChargeClass;
        @XmlAttribute(name = "next_selection_amount")
        protected String nextSelectionAmount;

        /**
         * Gets the value of the settings property.
         * 
         * @return
         *     possible object is
         *     {@link Rbt.Library.Settings }
         *     
         */
        public Rbt.Library.Settings getSettings() {
            return settings;
        }

        /**
         * Sets the value of the settings property.
         * 
         * @param value
         *     allowed object is
         *     {@link Rbt.Library.Settings }
         *     
         */
        public void setSettings(Rbt.Library.Settings value) {
            this.settings = value;
        }

        /**
         * Gets the value of the downloads property.
         * 
         * @return
         *     possible object is
         *     {@link Rbt.Library.Downloads }
         *     
         */
        public Rbt.Library.Downloads getDownloads() {
            return downloads;
        }

        /**
         * Sets the value of the downloads property.
         * 
         * @param value
         *     allowed object is
         *     {@link Rbt.Library.Downloads }
         *     
         */
        public void setDownloads(Rbt.Library.Downloads value) {
            this.downloads = value;
        }

        /**
         * Gets the value of the noOfFreeSongsLeft property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNoOfFreeSongsLeft() {
            return noOfFreeSongsLeft;
        }

        /**
         * Sets the value of the noOfFreeSongsLeft property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNoOfFreeSongsLeft(String value) {
            this.noOfFreeSongsLeft = value;
        }

        /**
         * Gets the value of the isAlbumUser property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsAlbumUser() {
            return isAlbumUser;
        }

        /**
         * Sets the value of the isAlbumUser property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsAlbumUser(String value) {
            this.isAlbumUser = value;
        }

        /**
         * Gets the value of the isRecentSelConsent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsRecentSelConsent() {
            return isRecentSelConsent;
        }

        /**
         * Sets the value of the isRecentSelConsent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsRecentSelConsent(String value) {
            this.isRecentSelConsent = value;
        }

        /**
         * Gets the value of the provideDefaultLoopOption property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProvideDefaultLoopOption() {
            return provideDefaultLoopOption;
        }

        /**
         * Sets the value of the provideDefaultLoopOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProvideDefaultLoopOption(String value) {
            this.provideDefaultLoopOption = value;
        }

        /**
         * Gets the value of the isMusicboxDefaultSettingPending property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsMusicboxDefaultSettingPending() {
            return isMusicboxDefaultSettingPending;
        }

        /**
         * Sets the value of the isMusicboxDefaultSettingPending property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsMusicboxDefaultSettingPending(String value) {
            this.isMusicboxDefaultSettingPending = value;
        }

        /**
         * Gets the value of the isClipDefaultSettingPending property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsClipDefaultSettingPending() {
            return isClipDefaultSettingPending;
        }

        /**
         * Sets the value of the isClipDefaultSettingPending property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsClipDefaultSettingPending(String value) {
            this.isClipDefaultSettingPending = value;
        }

        /**
         * Gets the value of the totalDownloads property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTotalDownloads() {
            return totalDownloads;
        }

        /**
         * Sets the value of the totalDownloads property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTotalDownloads(String value) {
            this.totalDownloads = value;
        }

        /**
         * Gets the value of the nextChargeClass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNextChargeClass() {
            return nextChargeClass;
        }

        /**
         * Sets the value of the nextChargeClass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNextChargeClass(String value) {
            this.nextChargeClass = value;
        }

        /**
         * Gets the value of the nextSelectionAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNextSelectionAmount() {
            return nextSelectionAmount;
        }

        /**
         * Sets the value of the nextSelectionAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNextSelectionAmount(String value) {
            this.nextSelectionAmount = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="contents" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{}content" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="recent_selections" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="charge_class" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="no_of_downloads" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="no_of_active_downloads" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "contents",
            "recentSelections"
        })
        public static class Downloads {

            protected Rbt.Library.Downloads.Contents contents;
            @XmlElement(name = "recent_selections")
            protected Rbt.Library.Downloads.RecentSelections recentSelections;
            @XmlAttribute(name = "no_of_downloads")
            protected String noOfDownloads;
            @XmlAttribute(name = "no_of_active_downloads")
            protected String noOfActiveDownloads;

            /**
             * Gets the value of the contents property.
             * 
             * @return
             *     possible object is
             *     {@link Rbt.Library.Downloads.Contents }
             *     
             */
            public Rbt.Library.Downloads.Contents getContents() {
                return contents;
            }

            /**
             * Sets the value of the contents property.
             * 
             * @param value
             *     allowed object is
             *     {@link Rbt.Library.Downloads.Contents }
             *     
             */
            public void setContents(Rbt.Library.Downloads.Contents value) {
                this.contents = value;
            }

            /**
             * Gets the value of the recentSelections property.
             * 
             * @return
             *     possible object is
             *     {@link Rbt.Library.Downloads.RecentSelections }
             *     
             */
            public Rbt.Library.Downloads.RecentSelections getRecentSelections() {
                return recentSelections;
            }

            /**
             * Sets the value of the recentSelections property.
             * 
             * @param value
             *     allowed object is
             *     {@link Rbt.Library.Downloads.RecentSelections }
             *     
             */
            public void setRecentSelections(Rbt.Library.Downloads.RecentSelections value) {
                this.recentSelections = value;
            }

            /**
             * Gets the value of the noOfDownloads property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoOfDownloads() {
                return noOfDownloads;
            }

            /**
             * Sets the value of the noOfDownloads property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoOfDownloads(String value) {
                this.noOfDownloads = value;
            }

            /**
             * Gets the value of the noOfActiveDownloads property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoOfActiveDownloads() {
                return noOfActiveDownloads;
            }

            /**
             * Sets the value of the noOfActiveDownloads property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoOfActiveDownloads(String value) {
                this.noOfActiveDownloads = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{}content" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class Contents {

                protected Content content;

                /**
                 * Gets the value of the content property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Content }
                 *     
                 */
                public Content getContent() {
                    return content;
                }

                /**
                 * Sets the value of the content property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Content }
                 *     
                 */
                public void setContent(Content value) {
                    this.content = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="charge_class" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class RecentSelections {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "charge_class")
                protected String chargeClass;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the chargeClass property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getChargeClass() {
                    return chargeClass;
                }

                /**
                 * Sets the value of the chargeClass property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setChargeClass(String value) {
                    this.chargeClass = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="contents" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{}content" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="no_of_default_settings" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="no_of_settings" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="no_of_special_settings" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "contents"
        })
        public static class Settings {

            protected Rbt.Library.Settings.Contents contents;
            @XmlAttribute(name = "no_of_default_settings")
            protected String noOfDefaultSettings;
            @XmlAttribute(name = "no_of_settings")
            protected String noOfSettings;
            @XmlAttribute(name = "no_of_special_settings")
            protected String noOfSpecialSettings;

            /**
             * Gets the value of the contents property.
             * 
             * @return
             *     possible object is
             *     {@link Rbt.Library.Settings.Contents }
             *     
             */
            public Rbt.Library.Settings.Contents getContents() {
                return contents;
            }

            /**
             * Sets the value of the contents property.
             * 
             * @param value
             *     allowed object is
             *     {@link Rbt.Library.Settings.Contents }
             *     
             */
            public void setContents(Rbt.Library.Settings.Contents value) {
                this.contents = value;
            }

            /**
             * Gets the value of the noOfDefaultSettings property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoOfDefaultSettings() {
                return noOfDefaultSettings;
            }

            /**
             * Sets the value of the noOfDefaultSettings property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoOfDefaultSettings(String value) {
                this.noOfDefaultSettings = value;
            }

            /**
             * Gets the value of the noOfSettings property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoOfSettings() {
                return noOfSettings;
            }

            /**
             * Sets the value of the noOfSettings property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoOfSettings(String value) {
                this.noOfSettings = value;
            }

            /**
             * Gets the value of the noOfSpecialSettings property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoOfSpecialSettings() {
                return noOfSpecialSettings;
            }

            /**
             * Sets the value of the noOfSpecialSettings property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoOfSpecialSettings(String value) {
                this.noOfSpecialSettings = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{}content" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class Contents {

                protected Content content;

                /**
                 * Gets the value of the content property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Content }
                 *     
                 */
                public Content getContent() {
                    return content;
                }

                /**
                 * Sets the value of the content property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Content }
                 *     
                 */
                public void setContent(Content value) {
                    this.content = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="CONSENT_SUBSCRIPTION_INSERT" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="VOLUNTARY" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="access_count" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="activated_by" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="activation_info" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="can_allow" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="circle_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="cos_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="is_prepaid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="is_valid_prefix" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="num_max_selections" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="pack" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="pca" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ref_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="subscriber_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="subscription_class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="user_type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="deactivated_by" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="last_deactivation_info" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="start_date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="end_date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="next_charging_date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="last_deactivation_date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="activation_date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="protocolNo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="protocolStaticText" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="next_billing_date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="charge_details" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="last_charge_amount" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="is_freemium_subscriber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="is_freemium" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="num_free_songs_left" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="is_uds_on" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="is_refundable" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="tobe_act_offer_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="offer_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="imei_no" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="scrn" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="scrs" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="DELAY_DEACT" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Subscriber {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "CONSENT_SUBSCRIPTION_INSERT")
        protected String consentsubscriptioninsert;
        @XmlAttribute(name = "VOLUNTARY")
        protected String voluntary;
        @XmlAttribute(name = "access_count")
        protected String accessCount;
        @XmlAttribute(name = "activated_by")
        protected String activatedBy;
        @XmlAttribute(name = "activation_info")
        protected String activationInfo;
        @XmlAttribute(name = "can_allow")
        protected String canAllow;
        @XmlAttribute(name = "circle_id")
        protected String circleId;
        @XmlAttribute(name = "cos_id")
        protected String cosId;
        @XmlAttribute(name = "is_prepaid")
        protected String isPrepaid;
        @XmlAttribute(name = "is_valid_prefix")
        protected String isValidPrefix;
        @XmlAttribute
        protected String language;
        @XmlAttribute(name = "num_max_selections")
        protected String numMaxSelections;
        @XmlAttribute
        protected String pack;
        @XmlAttribute
        protected String pca;
        @XmlAttribute(name = "ref_id")
        protected String refId;
        @XmlAttribute
        protected String status;
        @XmlAttribute(name = "subscriber_id")
        protected String subscriberId;
        @XmlAttribute(name = "subscription_class")
        protected String subscriptionClass;
        @XmlAttribute(name = "user_type")
        protected String userType;
        @XmlAttribute(name = "deactivated_by")
        protected String deactivatedBy;
        @XmlAttribute(name = "last_deactivation_info")
        protected String lastDeactivationInfo;
        @XmlAttribute(name = "start_date")
        protected String startDate;
        @XmlAttribute(name = "end_date")
        protected String endDate;
        @XmlAttribute(name = "next_charging_date")
        protected String nextChargingDate;
        @XmlAttribute(name = "last_deactivation_date")
        protected String lastDeactivationDate;
        @XmlAttribute(name = "activation_date")
        protected String activationDate;
        @XmlAttribute
        protected String protocolNo;
        @XmlAttribute
        protected String protocolStaticText;
        @XmlAttribute(name = "next_billing_date")
        protected String nextBillingDate;
        @XmlAttribute(name = "charge_details")
        protected String chargeDetails;
        @XmlAttribute(name = "last_charge_amount")
        protected String lastChargeAmount;
        @XmlAttribute(name = "is_freemium_subscriber")
        protected String isFreemiumSubscriber;
        @XmlAttribute(name = "is_freemium")
        protected String isFreemium;
        @XmlAttribute(name = "num_free_songs_left")
        protected String numFreeSongsLeft;
        @XmlAttribute(name = "is_uds_on")
        protected String isUdsOn;
        @XmlAttribute(name = "is_refundable")
        protected String isRefundable;
        @XmlAttribute(name = "tobe_act_offer_id")
        protected String tobeActOfferId;
        @XmlAttribute(name = "offer_id")
        protected String offerId;
        @XmlAttribute(name = "imei_no")
        protected String imeiNo;
        @XmlAttribute
        protected String scrn;
        @XmlAttribute
        protected String scrs;
        @XmlAttribute(name = "DELAY_DEACT")
        protected String delaydeact;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the consentsubscriptioninsert property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCONSENTSUBSCRIPTIONINSERT() {
            return consentsubscriptioninsert;
        }

        /**
         * Sets the value of the consentsubscriptioninsert property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCONSENTSUBSCRIPTIONINSERT(String value) {
            this.consentsubscriptioninsert = value;
        }

        /**
         * Gets the value of the voluntary property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVOLUNTARY() {
            return voluntary;
        }

        /**
         * Sets the value of the voluntary property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVOLUNTARY(String value) {
            this.voluntary = value;
        }

        /**
         * Gets the value of the accessCount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessCount() {
            return accessCount;
        }

        /**
         * Sets the value of the accessCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessCount(String value) {
            this.accessCount = value;
        }

        /**
         * Gets the value of the activatedBy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActivatedBy() {
            return activatedBy;
        }

        /**
         * Sets the value of the activatedBy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActivatedBy(String value) {
            this.activatedBy = value;
        }

        /**
         * Gets the value of the activationInfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActivationInfo() {
            return activationInfo;
        }

        /**
         * Sets the value of the activationInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActivationInfo(String value) {
            this.activationInfo = value;
        }

        /**
         * Gets the value of the canAllow property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCanAllow() {
            return canAllow;
        }

        /**
         * Sets the value of the canAllow property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCanAllow(String value) {
            this.canAllow = value;
        }

        /**
         * Gets the value of the circleId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCircleId() {
            return circleId;
        }

        /**
         * Sets the value of the circleId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCircleId(String value) {
            this.circleId = value;
        }

        /**
         * Gets the value of the cosId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCosId() {
            return cosId;
        }

        /**
         * Sets the value of the cosId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCosId(String value) {
            this.cosId = value;
        }

        /**
         * Gets the value of the isPrepaid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsPrepaid() {
            return isPrepaid;
        }

        /**
         * Sets the value of the isPrepaid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsPrepaid(String value) {
            this.isPrepaid = value;
        }

        /**
         * Gets the value of the isValidPrefix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsValidPrefix() {
            return isValidPrefix;
        }

        /**
         * Sets the value of the isValidPrefix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsValidPrefix(String value) {
            this.isValidPrefix = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the numMaxSelections property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumMaxSelections() {
            return numMaxSelections;
        }

        /**
         * Sets the value of the numMaxSelections property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumMaxSelections(String value) {
            this.numMaxSelections = value;
        }

        /**
         * Gets the value of the pack property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPack() {
            return pack;
        }

        /**
         * Sets the value of the pack property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPack(String value) {
            this.pack = value;
        }

        /**
         * Gets the value of the pca property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPca() {
            return pca;
        }

        /**
         * Sets the value of the pca property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPca(String value) {
            this.pca = value;
        }

        /**
         * Gets the value of the refId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefId() {
            return refId;
        }

        /**
         * Sets the value of the refId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefId(String value) {
            this.refId = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the subscriberId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubscriberId() {
            return subscriberId;
        }

        /**
         * Sets the value of the subscriberId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubscriberId(String value) {
            this.subscriberId = value;
        }

        /**
         * Gets the value of the subscriptionClass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubscriptionClass() {
            return subscriptionClass;
        }

        /**
         * Sets the value of the subscriptionClass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubscriptionClass(String value) {
            this.subscriptionClass = value;
        }

        /**
         * Gets the value of the userType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserType() {
            return userType;
        }

        /**
         * Sets the value of the userType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserType(String value) {
            this.userType = value;
        }

        /**
         * Gets the value of the deactivatedBy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeactivatedBy() {
            return deactivatedBy;
        }

        /**
         * Sets the value of the deactivatedBy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeactivatedBy(String value) {
            this.deactivatedBy = value;
        }

        /**
         * Gets the value of the lastDeactivationInfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastDeactivationInfo() {
            return lastDeactivationInfo;
        }

        /**
         * Sets the value of the lastDeactivationInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastDeactivationInfo(String value) {
            this.lastDeactivationInfo = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartDate(String value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEndDate(String value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the nextChargingDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNextChargingDate() {
            return nextChargingDate;
        }

        /**
         * Sets the value of the nextChargingDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNextChargingDate(String value) {
            this.nextChargingDate = value;
        }

        /**
         * Gets the value of the lastDeactivationDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastDeactivationDate() {
            return lastDeactivationDate;
        }

        /**
         * Sets the value of the lastDeactivationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastDeactivationDate(String value) {
            this.lastDeactivationDate = value;
        }

        /**
         * Gets the value of the activationDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActivationDate() {
            return activationDate;
        }

        /**
         * Sets the value of the activationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActivationDate(String value) {
            this.activationDate = value;
        }

        /**
         * Gets the value of the protocolNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProtocolNo() {
            return protocolNo;
        }

        /**
         * Sets the value of the protocolNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProtocolNo(String value) {
            this.protocolNo = value;
        }

        /**
         * Gets the value of the protocolStaticText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProtocolStaticText() {
            return protocolStaticText;
        }

        /**
         * Sets the value of the protocolStaticText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProtocolStaticText(String value) {
            this.protocolStaticText = value;
        }

        /**
         * Gets the value of the nextBillingDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNextBillingDate() {
            return nextBillingDate;
        }

        /**
         * Sets the value of the nextBillingDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNextBillingDate(String value) {
            this.nextBillingDate = value;
        }

        /**
         * Gets the value of the chargeDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChargeDetails() {
            return chargeDetails;
        }

        /**
         * Sets the value of the chargeDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChargeDetails(String value) {
            this.chargeDetails = value;
        }

        /**
         * Gets the value of the lastChargeAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastChargeAmount() {
            return lastChargeAmount;
        }

        /**
         * Sets the value of the lastChargeAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastChargeAmount(String value) {
            this.lastChargeAmount = value;
        }

        /**
         * Gets the value of the isFreemiumSubscriber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsFreemiumSubscriber() {
            return isFreemiumSubscriber;
        }

        /**
         * Sets the value of the isFreemiumSubscriber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsFreemiumSubscriber(String value) {
            this.isFreemiumSubscriber = value;
        }

        /**
         * Gets the value of the isFreemium property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsFreemium() {
            return isFreemium;
        }

        /**
         * Sets the value of the isFreemium property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsFreemium(String value) {
            this.isFreemium = value;
        }

        /**
         * Gets the value of the numFreeSongsLeft property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumFreeSongsLeft() {
            return numFreeSongsLeft;
        }

        /**
         * Sets the value of the numFreeSongsLeft property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumFreeSongsLeft(String value) {
            this.numFreeSongsLeft = value;
        }

        /**
         * Gets the value of the isUdsOn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsUdsOn() {
            return isUdsOn;
        }

        /**
         * Sets the value of the isUdsOn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsUdsOn(String value) {
            this.isUdsOn = value;
        }

        /**
         * Gets the value of the isRefundable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsRefundable() {
            return isRefundable;
        }

        /**
         * Sets the value of the isRefundable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsRefundable(String value) {
            this.isRefundable = value;
        }

        /**
         * Gets the value of the tobeActOfferId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTobeActOfferId() {
            return tobeActOfferId;
        }

        /**
         * Sets the value of the tobeActOfferId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTobeActOfferId(String value) {
            this.tobeActOfferId = value;
        }

        /**
         * Gets the value of the offerId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOfferId() {
            return offerId;
        }

        /**
         * Sets the value of the offerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOfferId(String value) {
            this.offerId = value;
        }

        /**
         * Gets the value of the imeiNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImeiNo() {
            return imeiNo;
        }

        /**
         * Sets the value of the imeiNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImeiNo(String value) {
            this.imeiNo = value;
        }

        /**
         * Gets the value of the scrn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScrn() {
            return scrn;
        }

        /**
         * Sets the value of the scrn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScrn(String value) {
            this.scrn = value;
        }

        /**
         * Gets the value of the scrs property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScrs() {
            return scrs;
        }

        /**
         * Sets the value of the scrs property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScrs(String value) {
            this.scrs = value;
        }

        /**
         * Gets the value of the delaydeact property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDELAYDEACT() {
            return delaydeact;
        }

        /**
         * Sets the value of the delaydeact property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDELAYDEACT(String value) {
            this.delaydeact = value;
        }

    }

}
