


/**
 * This is generated code and SHOULD NOT BE MODIFIED BY HAND. To change the transactions or the fields below, please regenerate.
 * If you have any questions, contact the Morpheus team.
 */
package com.onmobile.apps.ringbacktones.eventlogging.RBTSocialApp.v1_0_0;

import com.onmobile.reporting.framework.capture.api.Configuration;
import com.onmobile.reporting.framework.capture.api.ReportingException;

/**Captures all submanager transactions 
 */
public class EventLogger extends com.onmobile.reporting.framework.capture.api.TransactionBase {
	public static final String INNETWORK_Y = "Y";
	public static final String INNETWORK_N = "N";


	/**
	 * @param config Configuration of this logging system. Most important configuration item is the filepath to which logging should be done.
	 * @throws IOException if the initial log file cannot be created
	 */
	public EventLogger(Configuration config) throws java.io.IOException {
		super();
		initialize(config);
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getProduct()
	 */
	public String getProduct() {
		return "RBTSocialApp";
	}
	
	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getVersion()
	 */
	public String getVersion() {
		return "1.0.1";
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getFieldHeadings()
	 */
	protected String getFieldHeadings() {
		return "TIMESTAMP,TRANSTYPE,USER_ID,RBT_CIRCLE_ID,MSISDN,SENDER_ID,RBT_TYPE,TASK,OTHER_INFO,SOCIAL_TYPE,IN_NETWORK";
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#isAutoGeneratedTimestamp()
	 */
	protected boolean isAutoGeneratedTimestamp() {
		return false;
	}

	/**
	 * Log eventes whenever PIN is generated for Social App 
	 *
	 * @param timestamp Date for which data is being collected 
	 * @param userId Unique User Id of a user associated with a specific social site 
	 * @param msisdn msisdn for which transaction happened, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param senderId Id used to send SMS, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param otherInfo Any other information to be put here, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param socialType Id of a social site 
	*/
	public void SocailAppAccessLog(
		 java.util.Date timestamp
		,String userId
		,String msisdn
		,String senderId
		,String otherInfo
		,int socialType
	) throws ReportingException {
		StringBuffer buff = new StringBuffer();
		append(buff, timestamp);
		nextField(buff);// write field separator
		append(buff, "SocailAppAccessLog", false); // transType
		nextField(buff);// write field separator
		append(buff, userId, true);
		nextField(buff);// write field separator
		// skip field RbtCircleId not valid in this transaction
		nextField(buff);// write field separator
		append(buff, msisdn, false);
		nextField(buff);// write field separator
		append(buff, senderId, false);
		nextField(buff);// write field separator
		// skip field rbtType not valid in this transaction
		nextField(buff);// write field separator
		// skip field task not valid in this transaction
		nextField(buff);// write field separator
		append(buff, otherInfo, false);
		nextField(buff);// write field separator
		append(buff, socialType, 2147483647);
		nextField(buff);// write field separator
		// skip field inNetwork not valid in this transaction
		write(buff); // write record to file
	} // end of transaction function

	/**
	 * Log eventes whenever a user is validated through a social app 
	 *
	 * @param timestamp Date for which data is being collected 
	 * @param userId Unique User Id of a user associated with a specific social site 
	 * @param msisdn msisdn for which transaction happened, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param otherInfo Any other information to be put here, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param socialType Id of a social site 
	 * @param inNetwork Tells if MSISDN is from native network or not, values passed in should be enumerated from one of the constants
	 * beginning with INNETWORK_ defined in this class 
	*/
	public void SocailAppUservalidation(
		 java.util.Date timestamp
		,String userId
		,String msisdn
		,String otherInfo
		,int socialType
		,String inNetwork
	) throws ReportingException {
		StringBuffer buff = new StringBuffer();
		append(buff, timestamp);
		nextField(buff);// write field separator
		append(buff, "SocailAppUservalidation", false); // transType
		nextField(buff);// write field separator
		append(buff, userId, true);
		nextField(buff);// write field separator
		// skip field RbtCircleId not valid in this transaction
		nextField(buff);// write field separator
		append(buff, msisdn, false);
		nextField(buff);// write field separator
		// skip field senderId not valid in this transaction
		nextField(buff);// write field separator
		// skip field rbtType not valid in this transaction
		nextField(buff);// write field separator
		// skip field task not valid in this transaction
		nextField(buff);// write field separator
		append(buff, otherInfo, false);
		nextField(buff);// write field separator
		append(buff, socialType, 2147483647);
		nextField(buff);// write field separator
		append(buff, inNetwork, false);
		write(buff); // write record to file
	} // end of transaction function

	/**
	 * Log eventes whenever a user is activated for Social App 
	 *
	 * @param timestamp Date for which data is being collected 
	 * @param userId Unique User Id of a user associated with a specific social site 
	 * @param RbtCircleId Unique Id for the circle, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param msisdn msisdn for which transaction happened, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param rbtType RBT product type like RBT/RRBT, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param otherInfo Any other information to be put here, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param socialType Id of a social site 
	*/
	public void SocailAppSNGActivationLog(
		 java.util.Date timestamp
		,String userId
		,String RbtCircleId
		,String msisdn
		,String rbtType
		,String otherInfo
		,int socialType
	) throws ReportingException {
		StringBuffer buff = new StringBuffer();
		append(buff, timestamp);
		nextField(buff);// write field separator
		append(buff, "SocailAppSNGActivationLog", false); // transType
		nextField(buff);// write field separator
		append(buff, userId, true);
		nextField(buff);// write field separator
		append(buff, RbtCircleId, false);
		nextField(buff);// write field separator
		append(buff, msisdn, false);
		nextField(buff);// write field separator
		// skip field senderId not valid in this transaction
		nextField(buff);// write field separator
		append(buff, rbtType, false);
		nextField(buff);// write field separator
		// skip field task not valid in this transaction
		nextField(buff);// write field separator
		append(buff, otherInfo, false);
		nextField(buff);// write field separator
		append(buff, socialType, 2147483647);
		nextField(buff);// write field separator
		// skip field inNetwork not valid in this transaction
		write(buff); // write record to file
	} // end of transaction function

	/**
	 * Log eventes whenever a user is deactivated for Social App 
	 *
	 * @param timestamp Date for which data is being collected 
	 * @param userId Unique User Id of a user associated with a specific social site 
	 * @param RbtCircleId Unique Id for the circle, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param msisdn msisdn for which transaction happened, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param rbtType RBT product type like RBT/RRBT, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param otherInfo Any other information to be put here, caller should guarantee that no commas, carriage-returns or line-feeds are passed in 
	 * @param socialType Id of a social site 
	*/
	public void SocailAppSNGDeactivationLog(
		 java.util.Date timestamp
		,String userId
		,String RbtCircleId
		,String msisdn
		,String rbtType
		,String otherInfo
		,int socialType
	) throws ReportingException {
		StringBuffer buff = new StringBuffer();
		append(buff, timestamp);
		nextField(buff);// write field separator
		append(buff, "SocailAppSNGDeactivationLog", false); // transType
		nextField(buff);// write field separator
		append(buff, userId, true);
		nextField(buff);// write field separator
		append(buff, RbtCircleId, false);
		nextField(buff);// write field separator
		append(buff, msisdn, false);
		nextField(buff);// write field separator
		// skip field senderId not valid in this transaction
		nextField(buff);// write field separator
		append(buff, rbtType, false);
		nextField(buff);// write field separator
		// skip field task not valid in this transaction
		nextField(buff);// write field separator
		append(buff, otherInfo, false);
		nextField(buff);// write field separator
		append(buff, socialType, 2147483647);
		nextField(buff);// write field separator
		// skip field inNetwork not valid in this transaction
		write(buff); // write record to file
	} // end of transaction function

}


	
