package com.onmobile.apps.ringbacktones.daemons;

public enum RequestType
{
	SM_BASE_ACT, SM_BASE_DCT, 
	SM_SEL_ACT, SM_SEL_DCT,
	SM_SEL_REN,SM_SEL_ACT_DIR,
	SM_DWN_ACT, SM_DWN_DCT,
	SM_PACK_ACT, SM_PACK_DCT,
	SM_BASE_ACT_LOW, SM_SEL_ACT_LOW,
	PLAYER_BASE_ACT, PLAYER_BASE_DCT, PLAYER_BASE_SUS, 
	PLAYER_SEL_ACT, PLAYER_SEL_DCT,
	PLAYER_CHANGE_MSISDN,
	COPY_DIRECT, COPY_OPTOUT, COPY_OPTOUT_TIMEUP,
	COPY_OPTIN_KEYPRESS, COPY_OPTIN_ALWAYS, COPY_CONFIRMED,
	COPY_EXPIRED, AD_PARTNER_CALL_BACK
}
