//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 12:55:44 PM IST 
//


package com.onmobile.android.jaxb.downloads;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="previewFile" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="rbtFile" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="downloadStatus" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="setTime" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="selectedBy" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="chargeClass" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="isSetForAll" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "previewFile",
    "rbtFile",
    "downloadStatus",
    "categoryId",
    "setTime",
    "selectedBy",
    "chargeClass",
    "isSetForAll"
})
@XmlRootElement(name = "clip")
public class Clip {

    @XmlElement(required = true)
    protected Object previewFile;
    @XmlElement(required = true)
    protected Object rbtFile;
    @XmlElement(required = true)
    protected Object downloadStatus;
    @XmlElement(required = true)
    protected Object categoryId;
    @XmlElement(required = true)
    protected Object setTime;
    @XmlElement(required = true)
    protected Object selectedBy;
    @XmlElement(required = true)
    protected Object chargeClass;
    @XmlElement(required = true)
    protected Object isSetForAll;
    @XmlAttribute(required = true)
    protected BigInteger id;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected String type;

    /**
     * Gets the value of the previewFile property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPreviewFile() {
        return previewFile;
    }

    /**
     * Sets the value of the previewFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPreviewFile(Object value) {
        this.previewFile = value;
    }

    /**
     * Gets the value of the rbtFile property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRbtFile() {
        return rbtFile;
    }

    /**
     * Sets the value of the rbtFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRbtFile(Object value) {
        this.rbtFile = value;
    }

    /**
     * Gets the value of the downloadStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDownloadStatus() {
        return downloadStatus;
    }

    /**
     * Sets the value of the downloadStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDownloadStatus(Object value) {
        this.downloadStatus = value;
    }

    /**
     * Gets the value of the categoryId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCategoryId() {
        return categoryId;
    }

    /**
     * Sets the value of the categoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCategoryId(Object value) {
        this.categoryId = value;
    }

    /**
     * Gets the value of the setTime property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSetTime() {
        return setTime;
    }

    /**
     * Sets the value of the setTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSetTime(Object value) {
        this.setTime = value;
    }

    /**
     * Gets the value of the selectedBy property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSelectedBy() {
        return selectedBy;
    }

    /**
     * Sets the value of the selectedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSelectedBy(Object value) {
        this.selectedBy = value;
    }

    /**
     * Gets the value of the chargeClass property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getChargeClass() {
        return chargeClass;
    }

    /**
     * Sets the value of the chargeClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setChargeClass(Object value) {
        this.chargeClass = value;
    }

    /**
     * Gets the value of the isSetForAll property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIsSetForAll() {
        return isSetForAll;
    }

    /**
     * Sets the value of the isSetForAll property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIsSetForAll(Object value) {
        this.isSetForAll = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
