//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 12:55:44 PM IST 
//


package com.onmobile.android.jaxb.downloads;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.onmobile.android.jaxb.downloads package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.onmobile.android.jaxb.downloads
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Clip }
     * 
     */
    public Clip createClip() {
        return new Clip();
    }

    /**
     * Create an instance of {@link Downloads }
     * 
     */
    public Downloads createDownloads() {
        return new Downloads();
    }

    /**
     * Create an instance of {@link Clips }
     * 
     */
    public Clips createClips() {
        return new Clips();
    }

    /**
     * Create an instance of {@link Rbt }
     * 
     */
    public Rbt createRbt() {
        return new Rbt();
    }

}
