package com.onmobile.apps.ringbacktones.provisioning.common;

/**
 * This is generated code and SHOULD NOT BE MODIFIED BY HAND. To change the transactions or the fields below, please regenerate.
 * If you have any questions, contact the Morpheus team.
 */

import com.onmobile.reporting.framework.capture.api.Configuration;
import com.onmobile.reporting.framework.capture.api.ReportingException;

/**Interoperator copy transaction report. 
 */
public class DTWebsiteEventLogger extends com.onmobile.reporting.framework.capture.api.TransactionBase {

	/**
	 * @param config Configuration of this logging system. Most important configuration item is the filepath to which logging should be done.
	 * @throws IOException if the initial log file cannot be created
	 */
	public DTWebsiteEventLogger(Configuration config) throws java.io.IOException {
		super();
		initialize(config);
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getProduct()
	 */
	public String getProduct() {
		return "DTWebsiteTransLogger";
	}
	
	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getVersion()
	 */
	public String getVersion() {
		return "1.0.0";
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getFieldHeadings()
	 */
	protected String getFieldHeadings() {
		return "TIMESTAMP,TRANSTYPE,MSISDN,SONG__NAME,PROMO__ID,SMS__SENT,TYPE,INFO";
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#isAutoGeneratedTimestamp()
	 */
	protected boolean isAutoGeneratedTimestamp() {
		return false;
	}

	/**
	 * To store the website transactions. 
	 *
	 * @param timestamp Record time stamp of this transaction 
	 * @param msisdn Msisdn of subscriber 
	 * @param song_name Song Name of the content 
	 * @param promo_id Promo id of the content 
	 * @param sms_sent To identify if the sms has been sent or not 
	 * @param type To identify if it is a request or response from the customer 
	 * @param info Stores extra information about the transaction 
	*/
	public void DTWebsiteLogger(
		 java.util.Date timestamp
		,String msisdn
		,String song_name
		,String promo_id
		,String sms_sent
		,String type
		,String info
	) throws ReportingException {
		StringBuffer buff = new StringBuffer();
		append(buff, timestamp);
		nextField(buff);// write field separator
		append(buff, "DTWebsiteLogger", false); // transType
		nextField(buff);// write field separator
		append(buff, msisdn, true);
		nextField(buff);// write field separator
		append(buff, song_name, true);
		nextField(buff);// write field separator
		append(buff, promo_id, true);
		nextField(buff);// write field separator
		append(buff, sms_sent, true);
		nextField(buff);// write field separator
		append(buff, type, true);
		nextField(buff);// write field separator
		append(buff, info, true);
		write(buff); // write record to file
	} // end of transaction function

}

