package com.onmobile.apps.ringbacktones.provisioning.implementation.sms;

/**
 * This is generated code and SHOULD NOT BE MODIFIED BY HAND. To change the transactions or the fields below, please regenerate.
 * If you have any questions, contact the Morpheus team.
 */

import com.onmobile.reporting.framework.capture.api.Configuration;
import com.onmobile.reporting.framework.capture.api.ReportingException;

public class MOEventLogger extends com.onmobile.reporting.framework.capture.api.TransactionBase {

	/**
	 * @param config Configuration of this logging system. Most important configuration item is the filepath to which logging should be done.
	 * @throws IOException if the initial log file cannot be created
	 */
	public MOEventLogger(Configuration config) throws java.io.IOException {
		super();
		initialize(config);
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getProduct()
	 */
	public String getProduct() {
		return "MOREQUEST";
	}
	
	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getVersion()
	 */
	public String getVersion() {
		return "1.0.0";
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getFieldHeadings()
	 */
	protected String getFieldHeadings() {
		return "TIMESTAMP,TRANSTYPE,MSISDN,CIRCLE,SHORT_CODE,SMS_TEXT,REQUESTED_FEATURE,RESPONSE,CIRCLE_TYPE";
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#isAutoGeneratedTimestamp()
	 */
	protected boolean isAutoGeneratedTimestamp() {
		return false;
	}

	/**
	 * Transaction that indicates SMS requests from the subscriber 
	 *
	 * @param timestamp Time at which the request arrives 
	 * @param msisdn Msisdn of subscriber 
	 * @param circle Circle to which the subscriber belongs 
	 * @param shortCode Content Id in called operator 
	 * @param smsText SMS Text sent by the subscriber 
	 * @param requestedFeature Feature that the subscriber has requested for 
	 * @param response Response of the subscriber request SUCCESS/FAILURE 
	 * @param circleType Is the circle local, other OnMobile or Unknown 
	*/
	public void smsUITransaction(
		 java.util.Date timestamp
		,String msisdn
		,String circle
		,String shortCode
		,String smsText
		,String requestedFeature
		,String response
		,String circleType
	) throws ReportingException {
		StringBuffer buff = new StringBuffer();
		append(buff, timestamp);
		nextField(buff);// write field separator
		append(buff, "smsUITransaction", false); // transType
		nextField(buff);// write field separator
		append(buff, msisdn, true);
		nextField(buff);// write field separator
		append(buff, circle, true);
		nextField(buff);// write field separator
		append(buff, shortCode, true);
		nextField(buff);// write field separator
		append(buff, smsText, true);
		nextField(buff);// write field separator
		append(buff, requestedFeature, true);
		nextField(buff);// write field separator
		append(buff, response, true);
		nextField(buff);// write field separator
		append(buff, circleType, true);
		write(buff); // write record to file
	} // end of transaction function

}

