package com.onmobile.apps.ringbacktones.webservice.common;



/**
 * This is generated code and SHOULD NOT BE MODIFIED BY HAND. To change the transactions or the fields below, please regenerate.
 * If you have any questions, contact the Morpheus team.
 */

import com.onmobile.reporting.framework.capture.api.Configuration;
import com.onmobile.reporting.framework.capture.api.ReportingException;

/**Interoperator copy transaction report. 
 */
public class PPLContentRejectionLogger extends com.onmobile.reporting.framework.capture.api.TransactionBase {

	/**
	 * @param config Configuration of this logging system. Most important configuration item is the filepath to which logging should be done.
	 * @throws IOException if the initial log file cannot be created
	 */
	public PPLContentRejectionLogger(Configuration config) throws java.io.IOException {
		super();
		initialize(config);
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getProduct()
	 */
	public String getProduct() {
		return "PPLContentRejection";
	}
	
	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getVersion()
	 */
	public String getVersion() {
		return "1.0.0";
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#getFieldHeadings()
	 */
	protected String getFieldHeadings() {
		return "TIMESTAMP,TRANSTYPE,MSISDN,MODE,CLIP_ID,CATEGORY_ID";
	}

	/* (non-Javadoc)
	 * @see com.onmobile.reporting.framework.capture.api.TransactionBase#isAutoGeneratedTimestamp()
	 */
	protected boolean isAutoGeneratedTimestamp() {
		return false;
	}

	/**
	 * To save the rejected transaction. 
	 *
	 * @param msisdn Msisdn of subscriber who tried to make the selection 
	 * @param mode Mode through which subscriber tries to make selection 
	 * @param clipId Clip Id of the content 
	 * @param categoryId Category Id if the selection is shuffle 
	 * @param timestamp Record time stamp of this transaction 
	*/
	public void PPLContentRejectionTransaction(
		 String msisdn
		,String mode
		,String clipId
		,String categoryId
		,java.util.Date timestamp
	) throws ReportingException {
		StringBuffer buff = new StringBuffer();
		append(buff, timestamp);
		nextField(buff);// write field separator
		append(buff, "PPLContentRejectionTransaction", false); // transType
		nextField(buff);// write field separator
		append(buff, msisdn, true);
		nextField(buff);// write field separator
		append(buff, mode, true);
		nextField(buff);// write field separator
		append(buff, clipId, true);
		nextField(buff);// write field separator
		append(buff, categoryId, true);
		write(buff); // write record to file
	} // end of transaction function

}
