//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 12:55:57 PM IST 
//

package com.onmobile.android.jaxb.selections;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="callerId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="previewFile" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="rbtFile" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="fromTime" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="fromTimeMinutes" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="toTime" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="toTimeMinutes" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="selectionStatus" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="selectionType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="setTime" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="toTimeMinutes" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "content" })
@XmlRootElement(name = "clip")
public class Clip {

	@XmlElementRefs({
			@XmlElementRef(name = "fromTimeMinutes", type = JAXBElement.class),
			@XmlElementRef(name = "fromTime", type = JAXBElement.class),
			@XmlElementRef(name = "setTime", type = JAXBElement.class),
			@XmlElementRef(name = "callerId", type = JAXBElement.class),
			@XmlElementRef(name = "rbtFile", type = JAXBElement.class),
			@XmlElementRef(name = "categoryId", type = JAXBElement.class),
			@XmlElementRef(name = "status", type = JAXBElement.class),
			@XmlElementRef(name = "selectionType", type = JAXBElement.class),
			@XmlElementRef(name = "previewFile", type = JAXBElement.class),
			@XmlElementRef(name = "toTime", type = JAXBElement.class),
			@XmlElementRef(name = "toTimeMinutes", type = JAXBElement.class),
			@XmlElementRef(name = "selectionStatus", type = JAXBElement.class) })
	protected List<JAXBElement<Object>> content;
	@XmlAttribute(required = true)
	protected BigInteger id;
	@XmlAttribute(required = true)
	protected String name;
	@XmlAttribute(required = true)
	protected String type;

	/**
	 * Gets the rest of the content model.
	 * 
	 * <p>
	 * You are getting this "catch-all" property because of the following
	 * reason: The field name "ToTimeMinutes" is used by two different parts of
	 * a schema. See: line 71 of file:/E:/xjc/selections.xsd line 65 of
	 * file:/E:/xjc/selections.xsd
	 * <p>
	 * To get rid of this property, apply a property customization to one of
	 * both of the following declarations to change their names: Gets the value
	 * of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link Object }{@code >} {@link JAXBElement }
	 * {@code <}{@link Object }{@code >} {@link JAXBElement }{@code <}
	 * {@link Object }{@code >} {@link JAXBElement }{@code <}{@link Object }
	 * {@code >} {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * {@link JAXBElement }{@code <}{@link Object }{@code >} {@link JAXBElement }
	 * {@code <}{@link Object }{@code >} {@link JAXBElement }{@code <}
	 * {@link Object }{@code >} {@link JAXBElement }{@code <}{@link Object }
	 * {@code >} {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * {@link JAXBElement }{@code <}{@link Object }{@code >} {@link JAXBElement }
	 * {@code <}{@link Object }{@code >}
	 * 
	 * 
	 */
	public List<JAXBElement<Object>> getContent() {
		if (content == null) {
			content = new ArrayList<JAXBElement<Object>>();
		}
		return this.content;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setId(BigInteger value) {
		this.id = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

}
