//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 12:55:57 PM IST 
//

package com.onmobile.android.jaxb.selections;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.onmobile.android.jaxb.selections
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _ClipSetTime_QNAME = new QName("", "setTime");
	private final static QName _ClipCallerId_QNAME = new QName("", "callerId");
	private final static QName _ClipPreviewFile_QNAME = new QName("",
			"previewFile");
	private final static QName _ClipStatus_QNAME = new QName("", "status");
	private final static QName _ClipFromTimeMinutes_QNAME = new QName("",
			"fromTimeMinutes");
	private final static QName _ClipSelectionType_QNAME = new QName("",
			"selectionType");
	private final static QName _ClipRbtFile_QNAME = new QName("", "rbtFile");
	private final static QName _ClipCategoryId_QNAME = new QName("",
			"categoryId");
	private final static QName _ClipSelectionStatus_QNAME = new QName("",
			"selectionStatus");
	private final static QName _ClipFromTime_QNAME = new QName("", "fromTime");
	private final static QName _ClipToTime_QNAME = new QName("", "toTime");
	private final static QName _ClipToTimeMinutes_QNAME = new QName("",
			"toTimeMinutes");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.onmobile.android.jaxb.selections
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Clip }
	 * 
	 */
	public Clip createClip() {
		return new Clip();
	}

	/**
	 * Create an instance of {@link Clips }
	 * 
	 */
	public Clips createClips() {
		return new Clips();
	}

	/**
	 * Create an instance of {@link Settings }
	 * 
	 */
	public Settings createSettings() {
		return new Settings();
	}

	/**
	 * Create an instance of {@link Library }
	 * 
	 */
	public Library createLibrary() {
		return new Library();
	}

	/**
	 * Create an instance of {@link Rbt }
	 * 
	 */
	public Rbt createRbt() {
		return new Rbt();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "setTime", scope = Clip.class)
	public JAXBElement<Object> createClipSetTime(Object value) {
		return new JAXBElement<Object>(_ClipSetTime_QNAME, Object.class,
				Clip.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "callerId", scope = Clip.class)
	public JAXBElement<Object> createClipCallerId(Object value) {
		return new JAXBElement<Object>(_ClipCallerId_QNAME, Object.class,
				Clip.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "previewFile", scope = Clip.class)
	public JAXBElement<Object> createClipPreviewFile(Object value) {
		return new JAXBElement<Object>(_ClipPreviewFile_QNAME, Object.class,
				Clip.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "status", scope = Clip.class)
	public JAXBElement<Object> createClipStatus(Object value) {
		return new JAXBElement<Object>(_ClipStatus_QNAME, Object.class,
				Clip.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "fromTimeMinutes", scope = Clip.class)
	public JAXBElement<Object> createClipFromTimeMinutes(Object value) {
		return new JAXBElement<Object>(_ClipFromTimeMinutes_QNAME,
				Object.class, Clip.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "selectionType", scope = Clip.class)
	public JAXBElement<Object> createClipSelectionType(Object value) {
		return new JAXBElement<Object>(_ClipSelectionType_QNAME, Object.class,
				Clip.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "rbtFile", scope = Clip.class)
	public JAXBElement<Object> createClipRbtFile(Object value) {
		return new JAXBElement<Object>(_ClipRbtFile_QNAME, Object.class,
				Clip.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "categoryId", scope = Clip.class)
	public JAXBElement<Object> createClipCategoryId(Object value) {
		return new JAXBElement<Object>(_ClipCategoryId_QNAME, Object.class,
				Clip.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "selectionStatus", scope = Clip.class)
	public JAXBElement<Object> createClipSelectionStatus(Object value) {
		return new JAXBElement<Object>(_ClipSelectionStatus_QNAME,
				Object.class, Clip.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "fromTime", scope = Clip.class)
	public JAXBElement<Object> createClipFromTime(Object value) {
		return new JAXBElement<Object>(_ClipFromTime_QNAME, Object.class,
				Clip.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "toTime", scope = Clip.class)
	public JAXBElement<Object> createClipToTime(Object value) {
		return new JAXBElement<Object>(_ClipToTime_QNAME, Object.class,
				Clip.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "toTimeMinutes", scope = Clip.class)
	public JAXBElement<Object> createClipToTimeMinutes(Object value) {
		return new JAXBElement<Object>(_ClipToTimeMinutes_QNAME, Object.class,
				Clip.class, value);
	}

}
