//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 12:55:57 PM IST 
//


package com.onmobile.android.jaxb.selections;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}clips"/>
 *       &lt;/sequence>
 *       &lt;attribute name="noOfDefaultSettings" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="noOfSettings" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="noOfSpecialSettings" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clips"
})
@XmlRootElement(name = "settings")
public class Settings {

    @XmlElement(required = true)
    protected Clips clips;
    @XmlAttribute(required = true)
    protected BigInteger noOfDefaultSettings;
    @XmlAttribute(required = true)
    protected BigInteger noOfSettings;
    @XmlAttribute(required = true)
    protected BigInteger noOfSpecialSettings;

    /**
     * Gets the value of the clips property.
     * 
     * @return
     *     possible object is
     *     {@link Clips }
     *     
     */
    public Clips getClips() {
        return clips;
    }

    /**
     * Sets the value of the clips property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clips }
     *     
     */
    public void setClips(Clips value) {
        this.clips = value;
    }

    /**
     * Gets the value of the noOfDefaultSettings property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNoOfDefaultSettings() {
        return noOfDefaultSettings;
    }

    /**
     * Sets the value of the noOfDefaultSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNoOfDefaultSettings(BigInteger value) {
        this.noOfDefaultSettings = value;
    }

    /**
     * Gets the value of the noOfSettings property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNoOfSettings() {
        return noOfSettings;
    }

    /**
     * Sets the value of the noOfSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNoOfSettings(BigInteger value) {
        this.noOfSettings = value;
    }

    /**
     * Gets the value of the noOfSpecialSettings property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNoOfSpecialSettings() {
        return noOfSpecialSettings;
    }

    /**
     * Sets the value of the noOfSpecialSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNoOfSpecialSettings(BigInteger value) {
        this.noOfSpecialSettings = value;
    }

}
